# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mikes-nth.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Mike_S(n)
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "Mike Sanders blog on data science" # used by search engines

  # Header and footer text
  header_text: >
     <p><p style="font-size:58px">data science and general nerdery.</p>

  header_text_feature_image:
  footer_text: >
   Copyright 2017 Michael Sanders; all rights reserved.  Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "MikeS-nth"
  google_plus:
  instagram:
  linkedin:  http://www.linkedin.com/in/michael-j-sanders/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "notaverb"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems:
  - jemoji  
  [jekyll-paginate]
